### PR TITLE
Add IndexingProcessor

### PR DESCRIPTION
**Pull request by adjam**
There are quite a few changes here:

Adds 'solrtask' tool to aid in solr installation etc.
Add 'rsolr'
Add 'start.sh' startup script
Add a bunch of classes etc. to do the indexing

### CODE REVIEW

**Comment by adjam** [comment]
Note that this doesn't get you all the way to indexing stuff in Solr.  There's still some manual work in setting Solr up and creating a nearly-suitable 'data-driven' index.  See `start.sh` for more details.

**Comment by adjam** [comment]
bump

**Comment by queryluke** [comment]
fyi - If/when you add in the suffixer, we'll need to merge my latest changes

**Comment by adjam** [comment]
Assuming the suffixer can be wrapped as a pipeline stage, just add that to the pipeline defined in `app/services/indexing_processor.rb`; the existing stage definitions there should be enough to get you started.

**Pull request merged**
